import localFont from "next/font/local";
// import 'bootstrap/dist/css/bootstrap.min.css';
import Header from "./components/header";
import Footer from "./components/Footer";
import "./all.min.css"
import './fontawesome';
import "./style.css";

import "./globals.css";
import MobileNav from "./components/MobileNav";
import Orb from "./components/Orb";
import Topstrip from "./components/TopStrip";
import CustomCursor from "./components/CustomCursor";
import StickyPhone from "./components/Sticky";
import AppointmentButton from "./components/AppointmentButton";
import StickyBottomButton from "./components/StickyButton";
import BackToTopButton from "./components/ScrollTop";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <>
        <CustomCursor/>
        <StickyPhone/>
        <Topstrip/>
        <Header/>
        <Orb/>
        <MobileNav/>
        <StickyBottomButton/>
        {children}
        <BackToTopButton/>
        <Footer/>
        </>
      </body>
    </html>
  );
}
